spring:
  datasource:
    url: jdbc:h2:mem:nti-hw1-db
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
#      ddl-auto: none
    show-sql: true