drop table if exists students;
drop table if exists groups;
drop table if exists courses;
drop table if exists assignments;
drop table if exists grades;



create table groups
(
    id bigint generated by default as identity,
    name varchar(255)   not null,
    primary key (id)
);

create table students
(
    id bigint generated by default as identity,
    name varchar(255)   not null,
    group_id bigint not null,
    foreign key (group_id) references groups(id),
    primary key (id)
);

create table courses
(
    id bigint generated by default as identity,
    name varchar(255)   not null,
    primary key (id)
);

create table assignments
(
    id bigint generated by default as identity,
    name varchar(255)   not null,
    course_id bigint    not null,
    foreign key (course_id) references courses(id),
    primary key (id)
);

create table grades
(
    id bigint generated by default as identity,
    g_value bigint not null,
    student_id bigint not null,
    assignment_id bigint not null,
    foreign key (student_id) references students(id),
    foreign key (assignment_id) references assignments(id),
    primary key (id)
);
