clickhouse:
  host: localhost
  port: 8123
  database: hw2
  user: default
  password:

spring:
  sql:
    init:
      mode: always
  kafka:
    consumer:
      allow.auto.create.topics: true
      bootstrap-servers: localhost:9093
      properties:
        spring.json.trusted.packages: ru.mpei.*
      group-id: measurements
      auto-offset-reset: latest
      key-deserializer: ru.mpei.util.CustomDeserializer
      value-deserializer: ru.mpei.util.CustomDeserializer

    producer:
      allow.auto.create.topics: true
      bootstrap-servers: localhost:9093
      properties:
        spring.json.add.type.headers: true
      key-serializer: ru.mpei.util.CustomSerializer
      value-serializer: ru.mpei.util.CustomSerializer

topic:
  name:
    producer: measurements
    consumer: measurements